#theme = "solarized-dark"
icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
# rendering is broken
separator = ""

[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
#graph_down = true
interval = 1

#[[block]]
#block = "speedtest"
#bytes = true
#interval = 1800

[[block]]
block = "custom"
command = "echo \"WAN: $(curl ifconfig.co)\""
interval = 600 
on_click = 'curl -s ifconfig.co 2>/dev/null | tr -d "\n" | xclip -selection clipboard'

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "disk_space"
#path = "/home"
#alias = "~"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
#format = "{min}째 min, {max}째 max, {average}째 avg"
format = "{average}째 avg"

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#device = "BAT1"
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"

[[block]]
device = "BAT0"
block = "battery"
interval = 10
format = "{percentage}% {time}"


[[block]]
block = "sound"
on_click = "pavucontrol -t 3"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "gnome-calendar"

#[[block]]
#block = "toggle"
#text = "4k"
#command_state = "xrandr | grep DP1\\ connected\\ 38 | grep -v eDP1"
#command_on = "~/.screenlayout/4kmon_default.sh"
#command_off = "~/.screenlayout/builtin.sh"
#interval = 5
