(deftheme pink_2
  "Created 2019-05-24.")

(custom-theme-set-variables
 'pink_2
 '(ansi-color-names-vector ["#1b1a24" "#ee11dd" "#4c406d" "#b4f5fe" "#8CD0D3" "#DC8CC3" "#ffa500" "#8584ae"]))

(custom-theme-set-faces
 'pink_2
 '(button ((t (:underline t))))
 '(cursor ((t (:background "plum2" :foreground "#45444e"))))
 '(escape-glyph ((t (:foreground "#b4f5fe" :bold t))))
 '(fringe ((t (:background "#33144f" :foreground "slate blue"))))
 '(header-line ((t (:box (:line-width -1 :style released-button) :background "#28283f" :foreground "#b4f5fe"))))
 '(highlight ((t (:background "#503866"))))
 '(success ((t (:foreground "#4c406d" :weight bold))))
 '(warning ((t (:foreground "#8584ae" :weight bold))))
 '(tooltip ((t (:background "#33254d" :foreground "#8584ae"))))
 '(compilation-info ((t (:foreground "#DCA3A3"))))
 '(compilation-line-number ((t (:foreground "azure1"))))
 '(compilation-mode-line-exit ((t (:foreground "#4c406d" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#ee11dd" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "dark gray" :weight bold))))
 '(completions-annotations ((t (:foreground "#6565cc"))))
 '(match ((t (:background "#2F2F2F" :foreground "#8584ae" :weight bold))))
 '(isearch ((t (:foreground "#ffe000" :weight bold :background "#8584ae"))))
 '(isearch-fail ((t (:foreground "#8584ae" :background "#8C5353"))))
 '(lazy-highlight ((t (:background "#252634" :foreground "SlateBlue2" :weight bold))))
 '(menu ((t (:background "#2f202e" :foreground "#E06C75"))))
 '(minibuffer-prompt ((t (:foreground "#f4c5be"))))
 '(mode-line ((t (:background "#2f202e" :foreground "#DC8CC3"))))
 '(mode-line-buffer-id ((t (:foreground "#f4c5be" :weight bold))))
 '(mode-line-inactive ((t (:background "#2f202e" :foreground "#3c506d"))))
 '(region ((t (:background "#572755"))))
 '(secondary-selection ((t (:background "#44444"))))
 '(trailing-whitespace ((t (:background "#ee11dd"))))
 '(vertical-border ((t (:foreground "#8584ae"))))
 '(helm-header ((t (:background "#242429" :foreground "#7F9F7F" :box nil :underline nil))))
 '(helm-source-header ((t (:foreground "#F0DFAF" :background "#22222b" :underline nil :weight bold))))
 '(helm-selection ((t (:background "#4F4F4F" :underline nil))))
 '(helm-selection-line ((t (:background "#3F3F3F"))))
 '(helm-visible-mark ((t (:foreground "#3F3F3F" :background "#D0BF8F"))))
 '(helm-candidate-number ((t (:foreground "#BFEBBF" :background "#2B2B2B"))))
 '(helm-separator ((t (:foreground "#CC9393" :background "#3F3F3F"))))
 '(helm-buffer-not-saved ((t (:foreground "#CC9393" :background "#3F3F3F"))))
 '(helm-buffer-process ((t (:foreground "#93E0E3" :background "#3F3F3F"))))
 '(helm-buffer-saved-out ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(helm-buffer-size ((t (:foreground "#656555" :background "#3F3F3F"))))
 '(helm-ff-directory ((t (:foreground "#E06C75" :background "#23222f" :weight bold))))
 '(helm-ff-file ((t (:foreground "azure3" :background "#23222f" :weight normal))))
 '(helm-ff-executable ((t (:foreground "#9FC59F" :background "#23222f" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#CC9393" :background "#3F3F3F" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "#F0DFAF" :background "#23222f" :weight bold))))
 '(helm-ff-prefix ((t (:foreground "#3F3F3F" :background "#F0DFAF" :weight normal))))
 '(helm-grep-cmd-line ((t (:foreground "#93E0E3" :background "#3F3F3F"))))
 '(helm-grep-file ((t (:background "#662657" :foreground "#DCDCCC"))))
 '(helm-grep-finish ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(helm-grep-lineno ((t (:foreground "#656555" :background "#3F3F3F"))))
 '(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
 '(helm-match ((t (:background "#2B2B2B" :foreground "#E06C75" :weight bold))))
 '(helm-moccur-buffer ((t (:background "#662657" :foreground "#93E0E3"))))
 '(font-lock-builtin-face ((t (:foreground "misty rose"))))
 '(font-lock-comment-face ((t (:foreground "thistle4" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4c406d"))))
 '(font-lock-constant-face ((t (:foreground "#F0DFAF"))))
 '(font-lock-doc-face ((t (:foreground "#75baa8" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#61AFEF"))))
 '(font-lock-negation-char-face ((t (:foreground "#b4f5fe"))))
 '(font-lock-preprocessor-face ((t (:foreground "SlateBlue2"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b4f5fe" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#4c406d" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#98C379"))))
 '(font-lock-type-face ((t (:foreground "#E87DA6"))))
 '(font-lock-variable-name-face ((t (:foreground "#E06C75"))))
 '(font-lock-warning-face ((t (:foreground "#E06C75" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "plum2"))))
 '(anzu-mode-line ((t (:foreground "#E06C75" :weight bold))))
 '(anzu-match-1 ((t (:background "#4c78ad" :foreground "#23222f"))))
 '(anzu-match-2 ((t (:foreground "#23222f" :background "#8584ae"))))
 '(anzu-match-3 ((t (:background "#8CD0D3" :foreground "#23222f"))))
 '(anzu-replace-to ((t (:foreground "#23222f" :inherit anzu-replace-highlight))))
 '(avy-background-face ((t (:background "#23222f" :foreground "slate blue" :inverse-video nil))))
 '(avy-lead-face-0 ((t (:background "#23222f" :foreground "#75baa8" :inverse-video nil :weight bold))))
 '(avy-lead-face-1 ((t (:foreground "#b4f5fe" :background "#23222f" :inverse-video nil :weight bold))))
 '(avy-lead-face-2 ((t (:background "#23222f" :foreground "#DCA3A3" :inverse-video nil :weight bold))))
 '(avy-lead-face ((t (:background "#23222f" :foreground "#ffa500" :inverse-video nil :weight bold))))
 '(diff-added ((t (:background "#E06C75" :foreground "#4c406d"))))
 '(diff-changed ((t (:background "#555511" :foreground "#efef80"))))
 '(diff-removed ((t (:background "#553333" :foreground "#AC7373"))))
 '(diff-refine-added ((t (:background "#E06C75" :foreground "#ffe000"))))
 '(diff-refine-removed ((t (:background "#883333" :foreground "#ee11dd"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#8584ae")) (t (:background "#8584ae" :foreground "#23222f"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#8584ae" :foreground "#8584ae" :bold t)) (t (:background "#8584ae" :foreground "#23222f" :bold t))))
 '(diff-hl-change ((t (:background "dark slate blue" :foreground "#8CD0F3"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#DCA3A3" :background "#BC8383"))))
 '(diff-hl-insert ((t (:background "#6c808d" :foreground "#23222f"))))
 '(ediff-current-diff-A ((t (:foreground "#8584ae" :background "#8C5353"))))
 '(ediff-current-diff-Ancestor ((t (:foreground "#8584ae" :background "#8C5353"))))
 '(ediff-current-diff-B ((t (:background "#4c406d" :foreground "#8584ae"))))
 '(ediff-current-diff-C ((t (:foreground "#8584ae" :background "#23222f"))))
 '(ediff-even-diff-A ((t (:background "#4F4F4F"))))
 '(ediff-even-diff-Ancestor ((t (:background "#4F4F4F"))))
 '(ediff-even-diff-B ((t (:background "#4F4F4F"))))
 '(ediff-even-diff-C ((t (:background "#4F4F4F"))))
 '(ediff-fine-diff-A ((t (:foreground "#8584ae" :background "#AC7373" :weight bold))))
 '(ediff-fine-diff-Ancestor ((t (:foreground "#8584ae" :background "#AC7373" weight bold))))
 '(ediff-fine-diff-B ((t (:foreground "#8584ae" :background "#4c406d" :weight bold))))
 '(ediff-fine-diff-C ((t (:background "dark slate blue" :foreground "#8584ae" :weight bold))))
 '(ediff-odd-diff-A ((t (:background "#8584ae"))))
 '(ediff-odd-diff-Ancestor ((t (:background "#8584ae"))))
 '(ediff-odd-diff-B ((t (:background "#8584ae"))))
 '(ediff-odd-diff-C ((t (:background "#8584ae"))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#8584ae") :inherit unspecified)) (t (:foreground "#8584ae" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#ee11dd") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(hl-line ((t (:background "#422746"))))
 '(show-paren-mismatch ((t (:background "#ffa500" :foreground "red" :weight bold))))
 '(show-paren-match ((t (:background "#dda5cc" :foreground "#4c406d" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:background "#ffa500" :foreground "red" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#DC8CC3" :foreground "#4c406d" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#ffe000" :weight bold))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#BC8383" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#8584ae"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#b4f5fe"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#ffa500"))))
 '(vhl/default-face ((t (:background "#4f3a5e"))))
 '(whitespace-space ((t (:background "#4F4F4F" :foreground "#4F4F4F"))))
 '(whitespace-hspace ((t (:background "#4F4F4F" :foreground "#4F4F4F"))))
 '(whitespace-tab ((t (:background "#252634"))))
 '(whitespace-newline ((t (:foreground "#4F4F4F"))))
 '(whitespace-trailing ((t (:background "#252634"))))
 '(whitespace-line ((t (:background "#23222f" :foreground "#DC8CC3"))))
 '(whitespace-space-before-tab ((t (:background "#8584ae" :foreground "#8584ae"))))
 '(whitespace-indentation ((t (:background "#23222f" :foreground "#4c406d"))))
 '(whitespace-empty ((t (:background "#b4f5fe"))))
 '(whitespace-space-after-tab ((t (:background "#23222f" :foreground "#4c406d"))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#F0DFAF"))))
 '(default ((t (:background "#2f1e2e" :foreground "#c5d4de")))))

(provide-theme 'pink_2)
